feat: uniform package manager default version logic
Both npm and pnpm now default to the detected version, when the
version is omitted. In a case where pnpm is not detected, the latest
version will be installed.
This change also brings few minor improvements:
- Will not try to reinstall requested version if already installed
- Increase log points for easier debugging.

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -41,6 +41,21 @@ jobs:
               echo "pnpm version $PNPM_LATEST_VERSION not found"
               exit 1
             fi
+  ensure-pnpm-fresh-install:
+    docker:
+      - image: node:lts-slim
+    resource_class: medium
+    steps:
+      - core/ensure_pkg_manager:
+          ref: pnpm
+      - run:
+          name: Validate version
+          command: |
+            PNPM_LATEST_VERSION=$(npm view pnpm version)
+            if ! pnpm --version | grep -q "$PNPM_LATEST_VERSION"; then
+              echo "pnpm version $PNPM_LATEST_VERSION not found"
+              exit 1
+            fi
   install-dependencies-npm-node-18:
     executor:
       name: core/node_secrets
@@ -70,7 +85,7 @@ jobs:
       - core/install_dependencies:
           pkg_manager: pnpm@10.5.1
           pkg_json_dir: ~/project/sample
-          install_command: npm install
+          install_command: pnpm install
           cache_version: v10
       - run: cd ~/project/sample && npm run build
   run-script-npm:
@@ -105,6 +120,8 @@ workflows:
           filters: *filters
       - ensure-pnpm-version:
           filters: *filters
+      - ensure-pnpm-fresh-install:
+          filters: *filters
       - install-dependencies-npm-node-18:
           filters: *filters
       - install-dependencies-pnpm-node-18:
@@ -125,6 +142,7 @@ workflows:
             - orb-tools/pack
             - ensure-npm-version
             - ensure-pnpm-version
+            - ensure-pnpm-fresh-install
             - install-dependencies-npm-node-18
             - install-dependencies-pnpm-node-18
             - install-dependencies-custom-command
